<?php

/**
 * Implementation of hook_menu
 */
function sample_data_menu() {
  $items = array();
  
  $items["admin/config/sample-data"] = array(
    "title" => "Sample Data",
    "description" => "Load sample data into FlightPath's database.",
    "page_callback" => "fp_render_form",
    "page_arguments" => array("sample_data_install_form"),
    "access_arguments" => array("administer_sample_data"),
    "page_settings" => array(
      "page_has_search" => FALSE,
      "page_banner_is_link" => TRUE,
      "page_hide_report_error" => TRUE,
      "menu_links" => array(         
        0 => array(
          "text" => "Back to main menu",
          "path" => "admin-tools/admin",
        ),
      ),
    ),    
    "type" => MENU_TYPE_NORMAL_ITEM,
    "tab_parent" => "admin-tools/admin",    
  );         
 
  
  return $items;
}

function sample_data_perm() {
  return array("administer_sample_data" => array(
    "title" => t("trarabic_10511"),
    "description" => t("trarabic_20109"),
  ));
}

function sample_data_install_form() {
  $form = array();

  $form["mark" . $m++] = array(
    "value" => "<p>" . t("trarabic_20110") . "</p>",
  );
  
  $form["passcode"] = array(
    "type" => "textfield",
    "label" => t("trarabic_10512"),
    "description" => "Enter YES (all caps) to proceed.",
    
  );  
  
  $form["submit_btn"] = array(
    "type" => "submit",
    "value" => t("trarabic_10513"),
    "suffix" => "<p>" . t("trarabic_10514") . "</p>",
  );
  
  return $form;
  
}


function sample_data_install_form_validate($form, $form_state) {
  if ($form_state["values"]["passcode"] != "YES") {
    form_error("passcode", t("trarabic_10515"));
    return;
  }
}

/**
 * Actually perform the installation of data.
 */
function sample_data_install_form_submit($form, $form_state) {
  $file = fp_get_module_path("sample_data", TRUE, FALSE) . "/sample_data.sql";
  $sql = file_get_contents($file);
  
  // Okay, now we simply execute the contents of $sql, and we're good to go!
  // We need to split up the sql file into lines.
  $lines = explode("\n", $sql);
  foreach ($lines as $line) {
    $line = trim($line);
    // Does it start with TRUNCATE or INSERT?
    if (strstr($line, "INSERT") || strstr($line, "TRUNCATE") || strstr($line, "DELETE")) {
      db_query($line);
    }
  }
  
  // Clear our cache
  fp_clear_cache(); 
     
  fp_add_message(t("trarabic_20111"));
}



